config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("e_commerce_store.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path(
        "cart/",
        include("e_commerce_store.cart.urls", namespace="cart"),
        name="cart_add",
    ),
    path("orders/", include("e_commerce_store.orders.urls", namespace="orders")),
    path("payment/", include("e_commerce_store.payment.urls", namespace="payment")),
    path("", include("e_commerce_store.store.urls", namespace="store"), name="home"),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

e_commerce_store/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"
urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

e_commerce_store/orders/urls.py
from django.urls import path

from . import views

app_name = "orders"
urlpatterns = [
    path("create/", views.order_create, name="order_create"),
]

e_commerce_store/store/urls.py
from django.urls import path

from . import views

app_name = "store"
urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<slug:category_slug>/", views.product_list, name="product_list_by_category"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
]

e_commerce_store/users/urls.py
from django.urls import path

from e_commerce_store.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

e_commerce_store/orders/models.py
from django.conf import settings
from django.db import models

from e_commerce_store.store.models import Product
from e_commerce_store.users.models import User

# Create your models here.


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    stripe_id = models.CharField(max_length=250, blank=True)

    class Meta:
        ordering = ["-created"]
        indexes = [
            models.Index(fields=["-created"]),
        ]

    def __str__(self):
        return f"Order {self.id}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    def get_stripe_url(self):
        if not self.stripe_id:
            # no payment associated
            return ""
        if "_test_" in settings.STRIPE_SECRET_KEY:
            # Stripe path for test payments
            path = "/test/"
        else:
            # Stripe path for real payments
            path = "/"
        return f"https://dashboard.stripe.com{path}payments/{self.stripe_id}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name="order_items", on_delete=models.CASCADE
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

e_commerce_store/payment/models.py
# from django.db import models

# Create your models here.

e_commerce_store/store/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    """
    Category model for E-commerce store.
    """

    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["name"]),
        ]
        verbose_name = "category"
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse("store:product_list_by_category", args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    Product model for E-commerce store.
    One-to-many relationship with Category.
    """

    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    is_available = models.BooleanField(default=True)
    time_created = models.DateTimeField(auto_now_add=True)
    time_updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["id", "slug"]),
            models.Index(fields=["name"]),
            models.Index(fields=["-time_created"]),
        ]

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.id, self.slug])

    def __str__(self):
        return self.name

e_commerce_store/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for E-commerce store.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

e_commerce_store/cart/forms.py
# from crispy_forms.helper import FormHelper
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )
    quantity.widget.attrs.update({"class": "form-control mw-full"})

e_commerce_store/orders/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from .models import Order


class OrderCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        # self.helper.form_class = 'form-horizontal'
        self.helper.label_class = "col-auto col-sm-2 m-10 font-weight-bold"
        self.helper.field_class = "col ml-auto m-10"
        self.helper.form_method = "POST"
        self.helper.add_input(
            Submit("submit", "Continue", css_class="btn btn-lg btn-block mt-20")
        )

    class Meta:
        model = Order
        fields = ["address", "postal_code", "city"]

e_commerce_store/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

e_commerce_store/cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from e_commerce_store.store.models import Product

from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product, quantity=cd["quantity"], override_quantity=cd["override"]
        )
    return redirect("cart:cart_detail")


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(
            initial={"quantity": item["quantity"], "override": True}
        )
    return render(request, "cart/detail.html", {"cart": cart})

e_commerce_store/orders/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse

from e_commerce_store.cart.cart import Cart

from .forms import OrderCreateForm
from .models import OrderItem
from .tasks import order_created

# Create your views here.


@login_required
def order_create(request):
    cart = Cart(request)
    if request.method == "POST":
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item["product"],
                    price=item["price"],
                    quantity=item["quantity"],
                )
            # clear the cart
            cart.clear()

            # launch asynchronous task
            order_created.delay(order.id)
            # set the order in the session
            request.session["order_id"] = order.id
            # redirect for payment
            return redirect(reverse("payment:process"))

    else:
        form = OrderCreateForm()
    return render(request, "orders/order/create.html", {"cart": cart, "form": form})

e_commerce_store/payment/views.py
from decimal import Decimal

import stripe
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect, render, reverse

from e_commerce_store.orders.models import Order

# create the Stripe instance
stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


# Redirect to stripe payments


def payment_process(request):
    order_id = request.session.get("order_id", None)
    order = get_object_or_404(Order, id=order_id)
    if request.method == "POST":
        success_url = request.build_absolute_uri(reverse("payment:completed"))
        cancel_url = request.build_absolute_uri(reverse("payment:canceled"))
        # Stripe checkout session data
        session_data = {
            "mode": "payment",
            "client_reference_id": order.id,
            "success_url": success_url,
            "cancel_url": cancel_url,
            "line_items": [],
        }
        # add order items to the Stripe checkout session
        for item in order.items.all():
            session_data["line_items"].append(
                {
                    "price_data": {
                        "unit_amount": int(item.price * Decimal("100")),
                        "currency": "usd",
                        "product_data": {
                            "name": item.product.name,
                        },
                    },
                    "quantity": item.quantity,
                }
            )
        # create Stripe checkout session
        session = stripe.checkout.Session.create(**session_data)
        # redirect to Stripe payment form
        return redirect(session.url, code=303)
    else:
        return render(request, "payment/process.html", locals())


def payment_completed(request):
    return render(request, "payment/completed.html")


def payment_canceled(request):
    return render(request, "payment/canceled.html")

e_commerce_store/store/views.py
from django.shortcuts import get_object_or_404, render

from e_commerce_store.cart.forms import CartAddProductForm

from .models import Category, Product

# Create your views here.


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, is_available=True)
    cart_product_form = CartAddProductForm()
    return render(
        request,
        "store/product/detail.html",
        {"product": product, "cart_product_form": cart_product_form},
    )


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(is_available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(
        request,
        "store/product/list.html",
        {"category": category, "categories": categories, "products": products},
    )

e_commerce_store/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

e_commerce_store/templates/cart/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    Your shopping cart
{% endblock %}
{% block page-wrapper %}
    <div class="page-wrapper with-navbar">
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <h1 class="text-center font-weight-bold text-uppercase">Your shopping cart</h1>

        <section class="h-100" >
            <div class="container-fluid h-100 py-5">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-10">
                        {% for item in cart %}
                            {% with product=item.product %}
                                <div class="card rounded-3 mb-4 shadow-lg">
                                    <div class="card-body p-4">
                                        <div class="row d-flex justify-content-between align-items-center">
                                            <div class="col-md-2 col-lg-2 col-xl-2 justify-content-sm-center justify-content-md-start">
                                                <a href="{{ product.get_absolute_url }}">
                                                    <img src="{% if product.image %}{{ product.image.url }}
                                                    {% else %}{% static "img/no_image.png" %}{% endif %}" class="img-fluid rounded">
                                                </a>
                                            </div>
                                            <div class="col-md-3 col-lg-3 col-xl-3 justify-content-center justify-content-md-start">
                                                <p class="lead font-weight-bold text-capitalize">{{ product.name }}</p>
                                            </div>
                                            <div class="col-md-3 col-lg-3 col-xl-2 d-flex justify-content-center justify-content-md-start">
                                                <form action="{% url "cart:cart_add" product.id %}" method="post" class="mw-full">
                                                    {{ item.update_quantity_form.quantity }}
                                                    {{ item.update_quantity_form.override }}
                                                    <input type="submit" class="btn ml-auto mt-sm-10" value="Update">
                                                    {% csrf_token %}
                                                </form>
                                            </div>
                                            <div class="col col-md-3 col-lg-2 col-xl-2 offset-lg-1 justify-content-center">
                                                <h5 class="text-muted hidden-md-and-down text-center">Unit Price: </h5>
                                                <p class="font-weight-bold hidden-md-and-down text-center">${{ item.price }}</p>
                                                <h5 class="text-muted text-center">Total Price: </h5>
                                                <p class="font-weight-bold text-center">${{ item.total_price }}</p>
                                            </div>
                                            <div class="col-12 col-md-1 col-lg-1 col-xl-1 text-end justify-content-center">
                                                <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                                    <input type="submit" class="btn btn-block" value="X">
                                                    {% csrf_token %}
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endwith %}
                        {% endfor %}

                        <div class="card rounded-3 shadow-lg">
                            <div class="card-body">
                                <a type="button" class="btn btn-warning btn-block btn-lg mb-20"
                                    href="{% url "store:product_list" %}">
                                    Continue Shopping
                                </a>
                                <a type="button" class="btn btn-warning btn-block btn-lg"
                                    href="{% url "orders:order_create" %}">
                                    Proceed to Payment
                                </a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}